# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='deferred_writer',
    source=[
        'deferred_writer.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/base',
        '$VARIANT_DIR/mongo/db/catalog/collection',
    ],
    LIBDEPS_PRIVATE=[
        '$VARIANT_DIR/mongo/db/catalog/catalog_helpers',
        '$VARIANT_DIR/mongo/db/db_raii',
        '$VARIANT_DIR/mongo/util/concurrency/thread_pool',
    ],
)

env.Library(
    target='write_conflict_exception',
    source=[
        'write_conflict_exception.cpp',
        env.Idlc('write_conflict_exception.idl')[0],
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/base',
    ],
    LIBDEPS_PRIVATE=[
        '$VARIANT_DIR/mongo/idl/server_parameter',
        '$VARIANT_DIR/mongo/util/fail_point',
        '$VARIANT_DIR/mongo/util/log_and_backoff',
    ],
)

env.Library(
    target='lock_manager',
    source=[
        'd_concurrency.cpp',
        'lock_manager.cpp',
        'lock_state.cpp',
        'lock_stats.cpp',
        'replication_state_transition_lock_guard.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/base',
        '$VARIANT_DIR/mongo/db/service_context',
        '$VARIANT_DIR/mongo/util/background_job',
        '$VARIANT_DIR/mongo/util/concurrency/spin_lock',
        '$VARIANT_DIR/mongo/util/concurrency/ticketholder',
        '$VARIANT_DIR/third_party/shim_boost',
    ],
    LIBDEPS_PRIVATE=[
        '$VARIANT_DIR/mongo/db/catalog/collection_catalog',
        '$VARIANT_DIR/mongo/db/concurrency/flow_control_ticketholder',
    ],
)

env.Library(
    target='flow_control_ticketholder',
    source=[
        'flow_control_ticketholder.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$VARIANT_DIR/mongo/base',
    ],
)

env.Benchmark(
    target='lock_manager_bm',
    source=[
        'd_concurrency_bm.cpp',
    ],
    LIBDEPS=[
        'lock_manager',
    ])

env.CppUnitTest(
    target='db_concurrency_test',
    source=[
        'd_concurrency_test.cpp',
        'fast_map_noalloc_test.cpp',
        'lock_manager_test.cpp',
        'lock_state_test.cpp',
        'lock_stats_test.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/db/auth/authmocks',
        '$VARIANT_DIR/mongo/db/curop',
        '$VARIANT_DIR/mongo/db/service_context_d_test_fixture',
        '$VARIANT_DIR/mongo/util/progress_meter',
        'lock_manager',
        'write_conflict_exception',
    ]
)
