# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.Library(
    target='kv_prefix',
    source=['kv_prefix.cpp'],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/db/storage/storage_options',
    ],
)

# Should not be referenced outside this SConscript file.
env.Library(
    target='kv_drop_pending_ident_reaper',
    source=['kv_drop_pending_ident_reaper.cpp'],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/db/concurrency/lock_manager',
        '$VARIANT_DIR/mongo/db/storage/write_unit_of_work',
        'kv_prefix',
    ],
)

env.Library(
    target='kv_engine_test_harness',
    source=[
        'durable_catalog_feature_tracker_test.cpp',
        'kv_engine_test_harness.cpp',
        'kv_engine_timestamps_test.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/db/catalog/catalog_impl',
        '$VARIANT_DIR/mongo/db/service_context',
        '$VARIANT_DIR/mongo/db/service_context_test_fixture',
        '$VARIANT_DIR/mongo/db/storage/durable_catalog_impl',
        '$VARIANT_DIR/mongo/db/storage/storage_options',
        '$VARIANT_DIR/mongo/unittest/unittest',
        '$VARIANT_DIR/mongo/util/clock_source_mock',
        'kv_prefix',
    ],
)

env.CppUnitTest(
    target='db_storage_kv_engine_test',
    source=[
        'durable_catalog_test.cpp',
        'kv_drop_pending_ident_reaper_test.cpp',
        'storage_engine_test.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/db/auth/authmocks',
        '$VARIANT_DIR/mongo/db/catalog/collection_options',
        '$VARIANT_DIR/mongo/db/catalog_raii',
        '$VARIANT_DIR/mongo/db/namespace_string',
        '$VARIANT_DIR/mongo/db/repl/replmocks',
        '$VARIANT_DIR/mongo/db/service_context_d_test_fixture',
        '$VARIANT_DIR/mongo/db/service_context_test_fixture',
        '$VARIANT_DIR/mongo/db/storage/devnull/storage_devnull_core',
        '$VARIANT_DIR/mongo/db/storage/durable_catalog_impl',
        '$VARIANT_DIR/mongo/db/storage/ephemeral_for_test/ephemeral_for_test_record_store',
        '$VARIANT_DIR/mongo/db/storage/ephemeral_for_test/storage_ephemeral_for_test_core',
        '$VARIANT_DIR/mongo/db/storage/storage_engine_impl',
        '$VARIANT_DIR/mongo/db/storage/storage_repair_observer',
        'kv_drop_pending_ident_reaper',
    ],
)
