# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='cmdline_utils',
    source=[
        'censor_cmdline.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/base',
        '$VARIANT_DIR/mongo/util/options_parser/options_parser',
    ])

