# -*- mode: python -*-

Import("env")

env = env.Clone()

# Core geometry shape libraries
env.Library("geometry", [ "hash.cpp",
                          "shapes.cpp",
                          "big_polygon.cpp",
                          "r2_region_coverer.cpp" ],
            LIBDEPS = [ "$VARIANT_DIR/mongo/base",
                        "$VARIANT_DIR/mongo/db/common",
                        "$VARIANT_DIR/third_party/s2/s2" ])

# Geometry / BSON parsing and wrapping
env.Library("geoparser", [ "geoparser.cpp",
                           "geometry_container.cpp" ],
            LIBDEPS = [ "geometry",
                        "$VARIANT_DIR/mongo/base",
                        "$VARIANT_DIR/mongo/db/bson/dotted_path_support",
                        "$VARIANT_DIR/third_party/s2/s2" ])

env.CppUnitTest(
    target="db_geo_test",
    source=[
        "hash_test.cpp",
        "big_polygon_test.cpp",
        "geoparser_test.cpp",
        "r2_region_coverer_test.cpp",
    ],
    LIBDEPS=[
        "geometry",
        "geoparser",
        "$VARIANT_DIR/mongo/db/common"
    ]
)
