# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='thread_pool',
    source=[
        'thread_pool.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/base',
    ],
)

env.Library(
    target='thread_pool_test_fixture',
    source=[
        'thread_pool_test_common.cpp',
        'thread_pool_test_fixture.cpp'
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/unittest/unittest',
    ]
)

env.Library('ticketholder',
            ['ticketholder.cpp'],
            LIBDEPS=[
                '$VARIANT_DIR/mongo/base',
                '$VARIANT_DIR/mongo/db/service_context',
                '$VARIANT_DIR/third_party/shim_boost',
            ])

env.Library(
    target='spin_lock',
    source=[
        "spin_lock.cpp",
    ],
)

env.CppUnitTest(
    target='util_concurrency_test',
    source=[
        'spin_lock_test.cpp',
        'thread_pool_test.cpp',
        'ticketholder_test.cpp',
        'with_lock_test.cpp',
    ],
    LIBDEPS=[
        'spin_lock',
        'thread_pool',
        'thread_pool_test_fixture',
        'ticketholder',
    ]
)
