# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.Library(
    target='storage_biggie_core',
    source=[
        'biggie_kv_engine.cpp',
        'biggie_record_store.cpp',
        'biggie_recovery_unit.cpp',
        'biggie_sorted_impl.cpp',
        'biggie_visibility_manager.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/base',
        '$VARIANT_DIR/mongo/db/concurrency/write_conflict_exception',
        '$VARIANT_DIR/mongo/db/storage/index_entry_comparison',
        '$VARIANT_DIR/mongo/db/storage/kv/kv_prefix',
        '$VARIANT_DIR/mongo/db/storage/recovery_unit_base',
    ],
    LIBDEPS_PRIVATE=[
        '$VARIANT_DIR/mongo/db/storage/key_string',
        '$VARIANT_DIR/mongo/db/snapshot_window_options',
        '$VARIANT_DIR/mongo/db/storage/oplog_hack',
        '$VARIANT_DIR/mongo/db/storage/write_unit_of_work',
    ],
)

env.Library(
    target='storage_biggie',
    source=[
        'biggie_init.cpp',
    ],
    LIBDEPS=[
        '$VARIANT_DIR/mongo/db/storage/durable_catalog_impl',
        '$VARIANT_DIR/mongo/db/storage/storage_engine_impl',
        'storage_biggie_core',
    ],
    LIBDEPS_PRIVATE=[
        '$VARIANT_DIR/mongo/db/storage/storage_engine_common',
    ],
)

# Testing
env.CppUnitTest(
    target='storage_biggie_store_test',
    source=[
        'store_test.cpp',
    ],
)

env.CppUnitTest(
    target='biggie_record_store_test',
    source=['biggie_record_store_test.cpp'
            ],
    LIBDEPS=[
        'storage_biggie_core',
        '$VARIANT_DIR/mongo/db/storage/key_string',
        '$VARIANT_DIR/mongo/db/storage/record_store_test_harness'
        ],
)

env.CppUnitTest(
   target='biggie_sorted_data_interface_test',
   source=['biggie_sorted_impl_test.cpp'
           ],
   LIBDEPS=[
        'storage_biggie_core', 
        '$VARIANT_DIR/mongo/db/common',
        '$VARIANT_DIR/mongo/db/index/index_descriptor',
        '$VARIANT_DIR/mongo/db/storage/key_string',
        '$VARIANT_DIR/mongo/db/storage/sorted_data_interface_test_harness'
        ],
)

env.CppUnitTest(
   target='biggie_recovery_unit_test',
   source=['biggie_recovery_unit_test.cpp'
           ],
   LIBDEPS=[
        'storage_biggie_core',
        '$VARIANT_DIR/mongo/db/storage/recovery_unit_test_harness'
        ],
)

env.CppUnitTest(
   target='biggie_kv_engine_test',
   source=['biggie_kv_engine_test.cpp'
           ],
   LIBDEPS=[
        'storage_biggie_core',
        '$VARIANT_DIR/mongo/db/storage/kv/kv_engine_test_harness'
        ],
)
